#! /bin/sh

#Autostart
#nitrogen --restore &
xfce4-panel -d &
~/scripts/xmodmap.sh &
~/scripts/inicio.sh &
# ~/.screenlayout/compu-con-pantalla.sh &
arandr &
# nm-applet &
#xfdesktop -D &
sxhkd &
picom --config $HOME/.config/picom/picom.conf &

pgrep -x sxhkd >/dev/null || sxhkd &

# Más o menos funciona
# bspc monitor HDMI-0 -d 1 2 3 4 5
# bspc monitor eDP -d 6 7 8 9 0
amddp=$(xrandr --query | grep 'HDMI-0')

if [[ $amddp = *\ connected* ]]; then
	bspc monitor eDP -d - -
	bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 0
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

polybar -r &

bspc config border_width 3
bspc config window_gap 8
bspc config top_padding 22
bspc config single_monocle false
bspc config click_to_focus true
bspc config split_ratio 0.50
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
#Kanagawa
# bspc config normal_border_color "#2E3459"
# bspc config active_border_color "#DCA561"
# bspc config focused_border_color "#7E9CD8"
# bspc config presel_feedback_color "#5e81ac"
# bspc config urgent_border_color "#dd2727"
# Gruvbox Material
bspc config normal_border_color "#424a3e"
bspc config active_border_color "#7c6f64"
bspc config focused_border_color "#a89984"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"


bspc rule --add Gpick state=floating
bspc rule -a Xfce4-panel state=floating border=off
bspc rule -a xfce4-popup-whiskermenu state=floating border=off
bspc rule -a Whisker\ Menu state=floating border=off
bspc rule -a Wrapper-2.0 state=floating border=off focus=on
sleep 5 && xprop -name "Whisker Menu"
